### PR TITLE
Fix unicode endless loop

### LINKED ISSUE #98: inline goes into endless loop for unicode characters
Minimal example with unicode character π:

```js
txt = `
Algebra(2,0,1,()=>{
    console.log(π)
});`
var tokens = [
        // 0: whitespace/comments
        /^[\s\uFFFF]|^[\u000A\u000D\u2028\u2029]|^\/\/[^\n]*\n|^\/\*[\s\S]*?\*\//g,
        // 1: literal strings
        /^\"\"|^\'\'|^\".*?[^\\]\"|^\'.*?[^\\]\'|^\`[\s\S]*?[^\\]\`/g,
        // 2: literal numbers in scientific notation (with small hack for i and e_ asciimath)
        /^\d+[.]{0,1}\d*[ei][\+\-_]{0,1}\d*|^\.\d+[ei][\+\-_]{0,1}\d*|^e_\d*/g,
        // 3: literal hex, nonsci numbers and regex (surround regex with extra brackets!)
        /^\d+[.]{0,1}\d*[E][+-]{0,1}\d*|^\.\d+[E][+-]{0,1}\d*|^0x\d+|^\d+[.]{0,1}\d*|^\.\d+|^\(\/.*[^\\]\/\)/g,
        // 4: punctuator
        /^(\.Normalized|\.Length|\.\.\.|>>>=|===|!==|>>>|<<=|>>=|=>|\|\||[<>\+\-\*%&|^\/!\=]=|\*\*|\+\+|\-\-|<<|>>|\&\&|\^\^|^[{}()\[\];.,<>\+\-\*%|&^!~?:=\/]{1})/g,
        // 5: identifier
        /^[A-Za-z0-9_]*/g
    ];
tok = [];
resi = [];
while (txt.length) {
        for (t in tokens) {
            if (resi = txt.match(tokens[t])) {
                tok.push([t | 0, resi[0]]);
                txt = txt.slice(resi[0].length);
                break;
            } // tokenise
        }
    }

```

### PR DESCRIPTION
**Pull request by kungfooman**
This allows code like:

```js
// Create a Clifford Algebra with 3,0,1 metric. 
Algebra(3,0,1,()=>{
    var π = 3.14;
    var ℇℇℇ = 2.72;
    console.log("ππ is", π);
    console.log("ℇℇℇℇℇℇ is", ℇℇℇ);
});

```

Previously it would hang in an endless loop trying to process an empty token.

Fixes #98

### CODE REVIEW

File: ganja.js [hunk 1]
```diff
@@ -1454,7 +1454,7 @@
           /^\d+[.]{0,1}\d*[E][+-]{0,1}\d*|^\.\d+[E][+-]{0,1}\d*|^0x\d+|^\d+[.]{0,1}\d*|^\.\d+|^\(\/.*[^\\]\/\)/g,                       // 3: literal hex, nonsci numbers and regex (surround regex with extra brackets!)
           /^(\.Normalized|\.Length|\.\.\.|>>>=|===|!==|>>>|<<=|>>=|=>|\|\||[<>\+\-\*%&|^\/!\=]=|\*\*|\+\+|\-\-|<<|>>|\&\&|\^\^|^[{}()\[\];.,<>\+\-\*%|&^!~?:=\/]{1})/g,   // 4: punctuator
           /^[A-Za-z0-9_]*/g]                                                                                                            // 5: identifier
-        while (txt.length) for(t in tokens) if(resi=txt.match(tokens[t])){ tok.push([t|0,resi[0]]); txt=txt.slice(resi[0].length); break;} // tokenise
+        while (txt.length) for(t in tokens) if (resi = txt.match(tokens[t])) { var len = resi[0].length; if (len == 0) { var charCodes = []; for (var i=0; i<txt.length; i++) { var charCode = txt.charCodeAt(i); if (charCode > 255) charCodes.push(charCode); else break; } var codeString = String.fromCharCode(...charCodes); tok.push([t | 0, codeString]); txt = txt.slice(charCodes.length); } else { tok.push([t | 0, resi[0]]); txt = txt.slice(resi[0].length); } break; } // tokenise
```
Comment (eric-wieser) [inline ganja.js:1457]: Why 255?

Comment (kungfooman) [reply ganja.js]: Hey @eric-wieser, this way it will include all unicode characters in the identifier and stop whenever there is a normal/non-unicode character like a space, equal sign, comma, semicolon etc.

Comment (eric-wieser) [reply ganja.js]: Why is `255` your boundary for "normal" vs "not normal"?

I think the fix here is to ensure the regexes use the `u` unicode flag, rather than hacking something wrong-but-in-more-subtle-ways on the top.

File: ganja.js [hunk 2]
```diff
@@ -1454,7 +1454,7 @@
           /^\d+[.]{0,1}\d*[E][+-]{0,1}\d*|^\.\d+[E][+-]{0,1}\d*|^0x\d+|^\d+[.]{0,1}\d*|^\.\d+|^\(\/.*[^\\]\/\)/g,                       // 3: literal hex, nonsci numbers and regex (surround regex with extra brackets!)
           /^(\.Normalized|\.Length|\.\.\.|>>>=|===|!==|>>>|<<=|>>=|=>|\|\||[<>\+\-\*%&|^\/!\=]=|\*\*|\+\+|\-\-|<<|>>|\&\&|\^\^|^[{}()\[\];.,<>\+\-\*%|&^!~?:=\/]{1})/g,   // 4: punctuator
           /^[A-Za-z0-9_]*/g]                                                                                                            // 5: identifier
```
Comment (eric-wieser) [inline ganja.js:1456]: My guess is that the actual bug is on this line, and this should be something more like the regex in [this post](https://stackoverflow.com/a/6926184/102441),

```suggestion
          /^[$_\p{L}][$_\p{L}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\u200C\u200D]*+/gu]                                                                                                            // 5: identifier
```

I have neither tested this nor checked that the answer from that post is correct.

Comment (kungfooman) [reply ganja.js]: Hey @eric-wieser, thanks a lot for your review and code suggestion! I only had to remove the one-or-more `+` at the end of your unicode regex and it works great for everything I tested on it, like:

```js
"ℇℇasöäøæ09æøopüßdπ$π".match(/^[$_\p{L}][$_\p{L}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\u200C\u200D]*/gu)
```

image

I guess every browser should support unicode regexes nowadays, so that shouldn't be a problem.

**Review by enkimute — APPROVED** [review]
